# Configuraci贸n general de Spring Boot
spring:
  application:
    name: gestor-tareas

  # Configuraci贸n de la base de datos MongoDB
  data:
    mongodb:
      uri: mongodb://localhost:27017/manager-tasks

  # Configuraci贸n del servidor web
  web:
    servlet:
      context-path: /api
    port: 8080

  # Configuraci贸n de logging
  logging:
    level:
      root: INFO
      org.springframework.web: DEBUG